Page favorites
OlegNelasy/movies-project pull request #7
Opened 2023-04-13 11:26 UTC by OlegNelasy

made a favorites page

2023-04-13 14:21 UTC, AOnTeb9Celuet requested changes

2023-04-13 14:21 UTC, AOnTeb9Celuet commented on src/components/Header/Header.module.scss
> +        // }
remove comments

2023-04-13 14:21 UTC, AOnTeb9Celuet commented on src/components/Header/index.jsx
> +        </div> */}
remove comments

2023-04-13 14:21 UTC, AOnTeb9Celuet commented on src/pages/Favorites/Favorites.module.scss
> +                border: 2px solid $darck-color;
```suggestion
                border: 2px solid $dark-color;
```

2023-04-13 14:21 UTC, AOnTeb9Celuet commented on src/pages/Favorites/Favorites.jsx
> +  const getFavoriteMovies = async () => {
u dont need async right here cause this function doesnt have an async actions inside. Actually, u dont even need this function, just move the 11-12 lines code to the useEffect directly

2023-04-13 14:21 UTC, AOnTeb9Celuet commented on src/pages/Favorites/FavoriteMovie.jsx
> +        className={styles.unFavoriteButton}
```suggestion
        className={styles.unfavoriteButton}
```

2023-04-13 14:21 UTC, AOnTeb9Celuet commented on src/pages/Favorites/Favorites.module.scss
> +            .unFavoriteButton {
```suggestion
            .unfavoriteButton {
```

2023-04-13 18:02 UTC, OlegNelasy commented
Made corrections in a new commit

2023-04-13 18:03 UTC, OlegNelasy commented
Made corrections in a new commit

2023-04-14 15:31 UTC, AOnTeb9Celuet approved these changes

2023-04-14 15:31 UTC, merged